### ISSUE TITLE
aqara vrf ip地址问题

### ISSUE THREAD

**Issue by tzungtzu** [xswxm/hassio-addons#2]
请教一下，我通过路由器连接vrf网关，网关显示的地址还是默认的192.168.1.251，不是我路由器的网段，路由器内部显示lan连接但是也没显示ip地址，如何操作获取vrf网关的ip

**Comment by xswxm** [comment]
vrf恢复默认后他会有个默认的ip，比如说是192.168.1.251，确认电脑和vrf在同一网络内（可以用电脑直连vrf网关），把电脑的ip调整到vrf同一个网段内，如192.168.1.252，然后用电脑访问vrf，给vrf设置静态ip即可

**Comment by tzungtzu** [comment]
好的，另外还想问下，我是群晖下的ha，没有add-on，我把文件夹放入custom_components，在config里的写法不对
`
climate:
  - platform: zhonghong_vrf
`
，配置检查报错。

另外我看到作者你这个插件也支持docker，想问下怎么配置。

**Comment by tzungtzu** [comment]
@xswxm 
好的，另外还想问下，我是群晖下的ha，没有add-on，我把文件夹放入custom_components，在config里的写法不对
`
climate:
  -platform: zhonghong_vrf
`
配置检查报错。
另外我看到作者你这个插件也支持docker，想问下怎么配置。dockerhub上面没有写

**Comment by xswxm** [comment]
> 

1. 新的递交版本运行后会提示你如何手动添加configuration.yaml了
2. 本身插件就是基于docker的，你也可以自己直接git到本地，然后用dockerfile自行编译。也可以自己调整vrf.py的代码。默认配置是 /data/options.json。
